#! /bin/bash

    printf "> To configure Sync-Sh, you must have to provide the pairs of local directories and local files to be syncronized, with a corresponding alias to them, as follows:\n\n"
    sleep 1

    printf "> alias_dir: source_dir | target_dir\n> alias_file: source_file | target_file.\n"
    sleep 1
    printf "(use full paths)\n\n"
    sleep 1
    printf "You can leave the alias in blank. In this case, an alias will be automatically assigned.\n\n"
    sleep 1

    Nd=($(seq 1 100))
    IFS="|,:"

while : 
do

    printf "List your directory pairs. When finished, type \"done\" to proceed.\n\n"
    sleep 1

    for i in ${Nd[@]}; do
       read -r -p "${i}nd: " ad sd td
       echo "$ad $sd $td" >> /tmp/sync_dir.txt
        if [[ "$ad" == "done" || "$sd" == "done" || "$td" == "done" ]]; then
            break
        else
            continue
        fi
    done
    
    sleep 1
    printf "Now, list your file pairs.\n\n"
    sleep 1

    for i in ${Nd[@]}; do
       read -r -p "${i}nd: " af sf tf
       echo "$af $sf $tf" >> /tmp/sync_file.txt
        if [[ "$af" == "done" ||  "$sf" == "done" || "$tf" == "done" ]]; then
            break
        else
            continue
        fi
    done
    
    printf "The pairs of files and dirs to be syncronized are the following:\n\n"
    printf -- '%b\n' "DIRECTORIES PAIRS:\n$(cat /tmp/sync_dir.txt)\n-----------\n"
    printf '%b\n' "FILES PAIRS:\n$(cat /tmp/sync_file.txt)\n"

    printf "Are you sure? (y/yes or n/no)\n"

    read ok

    if  [[ $ok == "y" ||  $ok == "yes" ]]; then
        break
    else
        continue

    fi
    
done
    IFS=" "

# pedir para conferir a lista de diretórios para serem sincronizados.
            
